### ISSUE TITLE
Status of the bindings?

### ISSUE THREAD

**Issue by AndrejMitrovic** [cschlote/lmdb-d#1]
Hi @cschlote! 👋

I was recently looking at lmdb and wanted to see if there's a D binding of it anywhere, and found your repo.

What is the status of your bindings? Is it mostly complete / work in progress / or abandoned?

Your bindings seem to be targeting `v0.9.23`, there's been a few releases since then. I'm not sure if ldmb follows SemVer, so maybe there were no API changes since then.

Cheers!

**Comment by cschlote** [comment]
Hi Andrej,
I did not update the binding for a while. I will have a look on it the next time. 
I will use SemVer'ioning, so API changes will be relfected by the number. 
I hope, that there not to much breaking changes.
Regards
 Carsten
