### ISSUE TITLE
Incorrect size for string types

### ISSUE THREAD

**Issue by RobT2012** [cschlote/lmdb-d#2]
The below string constructors and the "assign" equivalents from MDB_Val do not work, they all use an incorrect byte size for the char array structure.

    this(const string data) nothrow {
        import std.string;
        this(toStringz(data), data.sizeof);
// replace .sizeof with .length+1 
// +1 is required to include the null termination char. 
    }

    /** Constructor to setup structure from a C string. */
    this(const char* data) nothrow {
        import core.stdc.string;
        this(data, strlen(data));
// strlen returns the length excluding the null termination char, you have to add +1 to include it
    }

See the "assign" functions, they have the same issue.

My suggestion is to keep it as simple as possible and only reproduce the bare bones bindings without adding any extra features to it.

**Comment by cschlote** [comment]
Hi, thanks for the review ;-) And yes, I will try to keep the bindings as simple as possible.
